### ISSUE TITLE
Introspection API

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#108]
Would be nice to have an introspection API that allows to read/interpret a complete routing tree. Includes:
- [x] a way to differenciate between different types of routes (instanceof)?
- [x] good toString implementations of routes?
- [x] access to attributes and attribute types

**Comment by lukasniemeier-zalando** [comment]
With such an API could enable a feature that _verifies_ the routing tree (i.e. preventing `NoRouteException`s) as an option?

**Comment by tkrop** [comment]
Good that you have removed it from 2.0.0. I have not understood the reason for an reflection API in the first place. Okay a good toString() is a value for itself, but how will you do this on lambdas?

Even to get a good route self-description, we must store context information of the specific lambda in the route (may be it should be called Target instead of Route), like how it was created and the description of its specific arguments, e.g. "capture(response)", or "call(runnable)". But I'm not sure whether this will create an additional value except for debugging.

@lukasniemeier-zalando this is already possible with the current API of RoutingTree - if you want to implement this feature.

**Comment by whiskeysierra** [comment]
> this is already possible with the current API of RoutingTree - if you want to implement this feature.

True, I already consider that part of the introspection. I guess we're not really missing much for this anyway.
