### ISSUE TITLE
Is there a plan to upgrade to Spring boot 3 & Spring 6?

### ISSUE THREAD

**Issue by KeshavRathi** [zalando/riptide#1351]
Is there a plan to upgrade to Spring boot 3 & Spring 6

## Context
A project of our uses Riptide and we wanted to upgrade the Spring version in it but can't as Riptide still uses the previous version and has few deprecated classes.

**Comment by fatroom** [comment]
We evaluating upgrade to spring boot 3, but no established timeline for a moment

**Comment by fatroom** [comment]
Steps needs to be performed to complete migration:

- [ ] switch to jdk17
- [ ] switch to apache components >= 5.1
- [ ] switch to Jakarta EE >= 9
- [ ] if compatible with Jakarta ee rest-client version exists switch to it, otherwise switch to okhttp mock server for testing
- [ ] accommodate spring changes in sync http client version

Open points:
1. deprecate async Http (?) / find the way to work with reactive spring? maybe outside of the basic spring 6 migration
2. evaluate interface based http clients and decide if can be supported?
