### ISSUE TITLE
Failsafe Starter: Endless retries by default

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/riptide#312]
Combining the starter with `riptide-failsafe` results in endless retries by default.

```
    my-service:
      base-url: https://foo.bar
```

In above's example user has not configured any `retry` configuration. Therefore default `retryPolicy` of `RetryPolicyFactoryBean` is used, which is configured to allow endless retries without delay (`maxRetries = -1`).

This seems unexpected, I'd expect **no delay** to be configured (`maxRetries = 0`). As soon as any other field is specified (e.g. `maxDuration`) delays should be allowed.

What do you think?

**Comment by whiskeysierra** [comment]
That was my intent.

**Comment by tkrop** [comment]
@whiskeysierra hmm, in my opinion an infinite retry is not a very sensible default. As an effect failures will result in resource consumption instead of backing off. A better way is to end the requests after a low number of retries with some default random backoff period. In cases where I used this concept the first retry could happen after even some milliseconds, while the second retry happened after a view seconds or a minute - to cover for handover and traffic switching situations.

Any other behavior requires manual configuration that takes the special knowledge about the system failures and their behaviors into account.

**Comment by whiskeysierra** [comment]
Sorry, what I meant is that it should not retry by default. See Lukas'
suggestion above
