### ISSUE TITLE
Throw runtime exceptions with nice message instead of AssertionError in Capture

### ISSUE THREAD

**Issue by jhorstmann** [zalando/riptide#43]

**Comment by lukasniemeier-zalando** [comment]
This is about https://github.com/zalando/riptide/blob/master/src/main/java/org/zalando/riptide/Capture.java#L51 ?

**Comment by jhorstmann** [comment]
Exactly, assertions should be used for programmer errors, in this case the throw can happen depending on the response from a server, so some runtime exception subclcass would be a better fit.

**Comment by whiskeysierra** [comment]
Based on the assumption that the server is implemented the API contract correctly (based on my gut feeling this is the more common case) the error is actually on the client side and therefore a programmer error, because the code to handle the response is not matching the contract (anymore/yet/...?).

**Comment by jhorstmann** [comment]
A very optimistic assumption. Still, the error is based on state only available at runtime, while assertions for me would be used for internal sanity checking or to make sure the programmer uses the api of a library correctly.

In this line I think just calling `get` on the optional would be the best solution.

**Comment by whiskeysierra** [comment]
@jhorstmann Happy with the change?

**Comment by jhorstmann** [comment]
:+1:  looks good
